version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sms_gateway_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_sms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sms_gateway_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cloud_sms_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sms_gateway_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
