"""Add extended device fields

Revision ID: 180fc107c44c
Revises: d65d18061052
Create Date: 2026-05-09 18:22:34.641171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180fc107c44c'
down_revision: Union[str, None] = 'd65d18061052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('phone_model', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('sim_count', sa.Integer(), nullable=True))
    op.drop_column('devices', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'sim_count')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'phone_model')
    op.drop_column('devices', 'device_name')
    # ### end Alembic commands ###
