"""add sim card fields

Revision ID: 56dfca062eec
Revises: 180fc107c44c
Create Date: 2026-05-13 12:45:49.854753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56dfca062eec'
down_revision: Union[str, None] = '180fc107c44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_cards', sa.Column('country_iso', sa.String(), nullable=True))
    op.add_column('sim_cards', sa.Column('network_operator', sa.String(), nullable=True))
    op.add_column('sim_cards', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('sim_cards', sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('sim_cards', 'last_reset_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_cards', sa.Column('last_reset_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('sim_cards', 'last_seen')
    op.drop_column('sim_cards', 'is_default')
    op.drop_column('sim_cards', 'network_operator')
    op.drop_column('sim_cards', 'country_iso')
    # ### end Alembic commands ###
