"""restore last_reset_at

Revision ID: bce3b6c10377
Revises: 56dfca062eec
Create Date: 2026-05-13 13:19:26.614019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce3b6c10377'
down_revision: Union[str, None] = '56dfca062eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhooks_id', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index('ix_user_settings_id', table_name='user_settings')
    op.drop_table('user_settings')
    op.add_column('sim_cards', sa.Column('last_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('sim_cards', 'network_operator')
    op.drop_column('sim_cards', 'is_default')
    op.drop_column('sim_cards', 'last_seen')
    op.drop_column('sim_cards', 'country_iso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_cards', sa.Column('country_iso', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sim_cards', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sim_cards', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sim_cards', sa.Column('network_operator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sim_cards', 'last_reset_at')
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_global_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retry_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smart_delay_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smart_delay_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('webhook_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_settings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey'),
    sa.UniqueConstraint('user_id', name='user_settings_user_id_key')
    )
    op.create_index('ix_user_settings_id', 'user_settings', ['id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='webhooks_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='webhooks_pkey')
    )
    op.create_index('ix_webhooks_id', 'webhooks', ['id'], unique=False)
    # ### end Alembic commands ###
