"""added more fields

Revision ID: d65d18061052
Revises: None
Create Date: 2026-05-09 16:24:04.434362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65d18061052'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_recipients', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('campaign_recipients', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('contact_group_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('total_messages', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('sent_messages', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('failed_messages', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'contact_groups', ['contact_group_id'], ['id'])
    op.add_column('sms_logs', sa.Column('sim_slot', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('country', sa.String(), nullable=False))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'country')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('sms_logs', 'sim_slot')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'scheduled_at')
    op.drop_column('campaigns', 'failed_messages')
    op.drop_column('campaigns', 'sent_messages')
    op.drop_column('campaigns', 'total_messages')
    op.drop_column('campaigns', 'contact_group_id')
    op.drop_column('campaign_recipients', 'error_message')
    op.drop_column('campaign_recipients', 'full_name')
    # ### end Alembic commands ###
